FROM node:22-alpine

WORKDIR /app

# 1. Instalar dependencias
COPY package*.json ./
RUN npm ci

# 2. Copiar Prisma y generar el cliente nativo para Linux de forma interna
COPY prisma ./prisma/
RUN npx prisma generate

# 3. Copiar el código fuente y COMPILAR AQUÍ (rápido y en caché de Docker)
COPY . .
RUN npm run build

EXPOSE 3000

CMD ["node", "dist/src/main.js"]